### ISSUE TITLE
I need help to fix this issue

### ISSUE THREAD

**Issue by ivandee** [thecodeholic/php-crash-course-2020#4]
Hello, this is the issue i am getting anytime i tried to submit the form without filling them up. I am trying to submit it empty to validate the errors array and the if statement i made

Fatal error: Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect decimal value: '' for column `products_crud`.`products`.`price` at row 1 in /opt/lampp/htdocs/start/a/14_product_crud/create.php:29 Stack trace: #0 /opt/lampp/htdocs/start/a/14_product_crud/create.php(29): PDOStatement->execute() #1 {main} thrown in /opt/lampp/htdocs/start/a/14_product_crud/create.php on line 29

**Comment by ivandee** [comment]
Thanks as i have get it fix and figured out

**Comment by Tapolog** [comment]
Have you tried form rendarring??
